// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequestManagement.API.Data;

#nullable disable

namespace RequestManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805093641_RenameSifreHashToSifre")]
    partial class RenameSifreHashToSifre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequestManagement.API.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("RequestManagement.API.Models.Talep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AtananKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TalepTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("RequestManagement.API.Models.TalepGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EskiDurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IslemYapanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("TalepId")
                        .HasColumnType("integer");

                    b.Property<string>("YeniDurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IslemYapanKullaniciId");

                    b.HasIndex("TalepId");

                    b.ToTable("TalepGecmisleri");
                });

            modelBuilder.Entity("RequestManagement.API.Models.TalepYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TalepId")
                        .HasColumnType("integer");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TalepId");

                    b.ToTable("TalepYorumlari");
                });

            modelBuilder.Entity("RequestManagement.API.Models.Talep", b =>
                {
                    b.HasOne("RequestManagement.API.Models.Kullanici", "AtananKullanici")
                        .WithMany()
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.API.Models.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtananKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("RequestManagement.API.Models.TalepGecmisi", b =>
                {
                    b.HasOne("RequestManagement.API.Models.Kullanici", "IslemYapanKullanici")
                        .WithMany()
                        .HasForeignKey("IslemYapanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestManagement.API.Models.Talep", "Talep")
                        .WithMany("Gecmis")
                        .HasForeignKey("TalepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IslemYapanKullanici");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("RequestManagement.API.Models.TalepYorum", b =>
                {
                    b.HasOne("RequestManagement.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestManagement.API.Models.Talep", "Talep")
                        .WithMany("Yorumlar")
                        .HasForeignKey("TalepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("RequestManagement.API.Models.Talep", b =>
                {
                    b.Navigation("Gecmis");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
