// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequestManagement.Infrastructure.Data;

#nullable disable

namespace RequestManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813114900_ForceAddAdSoyadToKullanici")]
    partial class ForceAddAdSoyadToKullanici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequestManagement.Domain.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.Talep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AtananKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.TalepGecmisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("EskiDurum")
                        .HasColumnType("integer");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TalepId")
                        .HasColumnType("uuid");

                    b.Property<int>("YeniDurum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TalepId");

                    b.ToTable("TalepGecmisleri");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.TalepYorum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TalepId")
                        .HasColumnType("uuid");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TalepId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.Talep", b =>
                {
                    b.HasOne("RequestManagement.Domain.Entities.Kullanici", "AtananKullanici")
                        .WithMany("AtananTalepler")
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Domain.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturulanTalepler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtananKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.TalepGecmisi", b =>
                {
                    b.HasOne("RequestManagement.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("TalepGecmisleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Domain.Entities.Talep", "Talep")
                        .WithMany("TalepGecmisleri")
                        .HasForeignKey("TalepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.TalepYorum", b =>
                {
                    b.HasOne("RequestManagement.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Domain.Entities.Talep", "Talep")
                        .WithMany("Yorumlar")
                        .HasForeignKey("TalepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("AtananTalepler");

                    b.Navigation("OlusturulanTalepler");

                    b.Navigation("TalepGecmisleri");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("RequestManagement.Domain.Entities.Talep", b =>
                {
                    b.Navigation("TalepGecmisleri");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
